### ISSUE TITLE
Run a pod with a specific user (non-root)

### ISSUE THREAD

**Issue by zeysh** [blablacar/dgr#152]
Hi,

Is there a way to run a pod with a dedicated user ?
Something similar to "set-user" with acbuild.

Many thanks.

**Comment by n0rad** [comment]
I dont' really know if you are taking about a single aci or a pod with multiple acis so here is for both.

Each aci in a pod has his own filesystem so you can set the running user by aci in the pod.
You can also set it for a single aci of course.

on aci:
```
aci:
  app:
    user: "0"
    group: "0"
```

on a pod
```
pod:
  apps:
    - dependencies:
        - aci.example.com/aci-toto
      app:
        user: "0"
        group: "0"
    - dependencies:
        - aci.example.com/aci-titi
      app:
        user: "0"
        group: "0"
   
```

also `app` node in pod are inherited from the dependency so you dont' have to set again

**Comment by n0rad** [comment]
Actually the app node is close to the app node of the appc spec https://github.com/appc/spec/blob/master/spec/aci.md.

except for :
- `eventHandlers` that is handled by dgr directly 
- `supplementaryGids`, that I have not implemented yet

**Comment by zeysh** [comment]
Hi @n0rad,

Thanks for your reply.
After some tests, I probably miss something...

Here the manifest
```
name: domain.net/elasticsearch:2.3.2
aci:
  dependencies:
    - domain.net/aci-base
    - domain.net/alpine-base
    - domain.net/alpine-java7
  app:
    user: "0"
    group: "0"
    exec: [ /opt/elasticsearch-2.3.2/bin/elasticsearch ]
    workingDirectory: /opt/elasticsearch-2.3.2/bin
    mountPoints:
      - {name: data, path: /var/lib/elasticsearch, readOnly: false}
      - {name: config, path: /opt/elasticsearch-2.3.2/config, readOnly: false}
```

When I run my aci image with --user=1000 I got this issue
```
sudo rkt run --insecure-options=image target/image.aci --user=1000
...
[ 5943.720229] elasticsearch[5]: chmod: /dgr/runlevels/prestart-early/00.early.sh: Operation not permitted
```

Any idea ?
Many thanks
