### ISSUE TITLE
Using local custom rootfs

### ISSUE THREAD

**Issue by f0** [blablacar/dgr#199]
Hi,

is there a way to use a rootfs from a local tarball, or how can i access files from the builder in the rootdir?

regards f0

**Comment by n0rad** [comment]
You can use mount points to the builder
```
builder:
  mountPoints:
    - {from: ../, to: /code}
```

@blablacar, we are using it to build code project in the builder and output as an aci:

```
name: example.com/dummy
builder:
  dependencies:
    - example.com/aci-maven
    - example.com/aci-java
  mountPoints:
    - {from: ../, to: /code}
    - {from: ~/.m2, to: /root/.m2}
```
