### ISSUE TITLE
how do i  mount host volumes while building?

### ISSUE THREAD

**Issue by biax** [blablacar/dgr#206]
i have my own private local apk repository of selfbuilt custom apk packages on my host system (/opt/apk-private/apklocal) i wish to do something like **apk add --no-cache --repository /var/lib/apklocal custom.apk**

so basically i want the mount only while building to install the package but no mount when running the pod.

i believe my aci-manifest.yml is wrong. anyone able to point out my error?

```
name: private.local/alpine-nginx
builder:
  mountPoints:
    - { from: /opt/apk-private/apklocal, to: /var/lib/apklocal }
aci:
  dependencies:
    - private.local/alpine-base
  app:
    exec:
      - /bin/bash
```
