### ISSUE TITLE
Resource isolators are skipped

### ISSUE THREAD

**Issue by wmark** [blablacar/dgr#211]
I am using **dgr** version 77 and **rkt** 1.19.0, though I believe the latter does not matter.

My `aci-manifest.yml`:
```yaml
name: example/minimal:1

aci:
  app:
    isolators:
      - name: resource/memory
        value: {request: 32M, limit: 256M}
      - name: resource/cpu
        value: {request: 125m, limit: 500m}
  dependencies:
    - 'blitznote.com/ubuntu:16.04'
```

… is translated to (please observe the **isolators**):
```json
{
  "acKind": "ImageManifest",
  "acVersion": "0.8.1",
  "name": "example/minimal",
  "labels": [
    {"name": "version", "value": "1"},
    {"name": "os", "value": "linux"},
    {"name": "arch", "value": "amd64"}
  ],
  "app": {
    "eventHandlers": [
      {"name": "pre-start", "exec": ["/dgr/bin/prestart"]}
    ],
    "isolators": [
      {
        "name": "resource/memory",
        "value": {"set": null}
      },
      {
        "name": "resource/cpu",
        "value": {"set": null}
      }
    ]
  },
  "dependencies": [
    {"imageName": "blitznote.com/ubuntu", "labels": [{"name": "version", "value": "16.04"}]}
  ]
}
```

Yet I do expect this:
```json
…
    "isolators": [
      {
        "name": "resource/memory",
        "value": {"request": "32M", "limit": "256M"}
      },
      {
        "name": "resource/cpu",
        "value": {"request": "125m", "limit": "500m"}
      }
    ]
  },
…
```
See also [appc/spec/schema/types/isolator_resources.go](https://github.com/blablacar/dgr/blob/ee9aafa511c095b19cf0f8c98abb9932aa252784/vendor/github.com/appc/spec/schema/types/isolator_resources.go#L64-L68).

**Comment by nyodas** [comment]
Hi
It should work with 
```
name: example/minimal:1

aci:
  app:
    isolators:
      - name: resource/memory
        value: {request: 32M, limit: 256M}
      - name: resource/cpu
        value: {request: 125m, limit: 500m}
  dependencies:
    - 'blitznote.com/ubuntu:16.04'
```
