### ISSUE TITLE
Using builder dependencies

### ISSUE THREAD

**Issue by crackcomm** [blablacar/dgr#231]
When I tried to use

```yaml
builder:
  dependencies:
    - dependency…
```

I got an error that is impossible to get `blablacar.github.io/dgr/aci-builder` although it works when no builder dependencies are used.

I am having hard time uploading `dist/bindata/aci-builder.aci` file to `acserver`, could you assist me with one or another?

Thanks
