### ISSUE TITLE
[confd] Scientific Notation for big integer

### ISSUE THREAD

**Issue by mfouilleul** [blablacar/dgr#85]
Confd formats large integer with the scientific notation. Can be avoided by adding quotes on attributes (temporary fix).

**Comment by n0rad** [comment]
reopen if still happen with new templater

**Comment by mfouilleul** [comment]
Stil happen with the new templater:

Attributes file:
```
---
override:
  maxscale:
    binlogrouter:
      master_id: 3232235530
```

Template:
```
master-id={{ $data.maxscale.binlogrouter.master_id }}
```

Result in final file:
```
master-id=3.23223553e+09
```

It can be stil avoided by adding some quotes:
```
---
override:
  maxscale:
    binlogrouter:
      master_id: "3232235530"
```

Max.
